version: '3'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=dev_dte
    volumes:
      - db-data:/var/lib/mysql:cached

  redis:
    image: redis:alpine
    ports:
      - "63790:6379"

volumes:
  db-data:
